### ISSUE TITLE
No path should be more than 15 chars

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-infrastructure#1]

**Comment by davidmegginson** [comment]
@cjhendrix — could you provide more details about this issue?

**Comment by cjhendrix** [comment]
If I remember correctly, this was raised by Serban and we made a quick issue so that we wouldn't forget.   Though now of course I've forgotten why he was worried about it.-----David Megginson notifications@github.com wrote: -----

To: OCHA-DAP/hdx-infrastructure hdx-infrastructure@noreply.github.com
From: David Megginson notifications@github.comDate: 05/02/2014 10:39AM
Cc: cjhendrix hendrix@un.orgSubject: Re: [hdx-infrastructure] No path should be more than 15 chars (#1)@cjhendrix
 — could you provide more details about this issue?—Reply to this email directly or 
view it on GitHub.

**Comment by teodorescuserban** [comment]
it is done.
