### ISSUE TITLE
Deployment scripts adjustements

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-infrastructure#100]
I think we need to improve our deployment scripts by adding a parameter to deploy a specific tag (this should be available for all servers):
- in case there is NO param it will deploy the branch (dev/staging/prod)
- in case there is a param it will deploy the tag which is = with the value of the param

**Comment by teodorescuserban** [comment]
Done by having a CKAN_BRANCH env variable in the Dockerfile.
When building the image, the selected branch / tag will be built.
