### ISSUE TITLE
Change to /ebola sort order

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-infrastructure#101]
From ST: 
before I forget, can you change the default behavior on the /ebola page to sort by last modified instead of relevance? https://data.hdx.rwlabs.org/ebola

**Comment by teodorescuserban** [comment]
Will do. Easy.

**Comment by teodorescuserban** [comment]
Done.
Now `/ebola` goes to `/dataset?q=ebola&sort=metadata_modified+desc` instead of just `/dataset?q=ebola`
