### ISSUE TITLE
dockerize ckan

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#102]
Relatively simple until I hit https://github.com/ckan/ckan/issues/1730

**Comment by rufuspollock** [comment]
Just to check: you know ckan core is dockerized and dedicated repo for ckan dockerization stuff is https://github.com/ckan/ckan-docker

**Comment by teodorescuserban** [comment]
Yes, but as you might know, we are using our forked ckan version :(
I will double check that link you gave me.
Thank you.

**Comment by teodorescuserban** [comment]
Update @rgrp : ckan dockerfile is still broken but good enough to be inspired by it. :)
Thanks again.

**Comment by teodorescuserban** [comment]
done.
still needs dataproxy..

**Comment by rufuspollock** [comment]
@teodorescuserban if ckan docker file is broken do please report it on that repo :-)

**Comment by rufuspollock** [comment]
@teodorescuserban also please could you report on that repo (maybe in an issue) your experience and your work - in terms of your own work going forward it will obviously help you if your changes get merged upstream (also how have you forked ckan and are you pushing changes upstream?)

**Comment by teodorescuserban** [comment]
It's just old and incomplete.
Also the description does not contain additional scripts used for that image.
So what I did, I just started from phusion/base-docker and made the following images:
hdx-base (base image for all our dockers) from which I built
hdx-base-python (base image for all our python apps) from which I built
hdx-base-ckan (base image for all our ckan dockers) from which I built 
hdx-ckan (image with prod branch of our hdx ckan fork with all our plugins configured and ready to run)

Also, from
hdx-base I made
hdx-base-psql (base image for all out postgres dockers) from which I built
hdx-psql-ckan (postgresql image ready to be linked with a hdx-ckan container)

Also, from
hdx-base I made
hdx-solr (uses solr 4.8.1) - ckan solr dockerfile is broken :)

Also from 
hdx-python I built 
hdx-dataproxy (image ready for spinning new dataproxy containers for hdx-ckan with @mbellotti 's fork of dataproxy)

Datapusher image is on the way :)

**Comment by teodorescuserban** [comment]
Basically, assuming I already have ckan db and datastore db configured in a folder on my docker's host, I can spin up all ckan deps with one command :)
