### ISSUE TITLE
Help cj troubleshoot vpn and curl

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-infrastructure#114]
I'm a bit stuck with VPN and curl.  This is not an urgent issue, but I would like to resolve it sometime in January.
1. VPN will not connect on my home computer (I'll add a screenshot of the error later)
2. At work, VPN works, but with an error: 
   ![image](https://cloud.githubusercontent.com/assets/1654485/5536305/8d132be8-8a8f-11e4-9d89-7a1c90cd31d4.png)
3. Using cURL against stag doesn't work, returning: `curl: (35) Unknown SSL protocol error in connection to . . .`

**Comment by teodorescuserban** [comment]
@cjhendrix please ping me tomorrow (tuesday) around your 10:30AM
