### ISSUE TITLE
Changes to nginx to be able to see the rq-monitor

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-infrastructure#120]
Nginx should map some URL to  http://GIS-REST-LAYER-HOST/monitor/

Also the same information can be seen from command line like this:
`rqinfo --url redis://redis:6379/1`
Maybe we can add this to hdxckantool. **One thing to NOTE though**: For the _rqinfo_ tool to be available you need: `pip install rq` ( so for now this would only work in the GISRestLayer container )

More information about this can be found here:
https://docs.google.com/document/d/1trUidBNY996wW-Qw55k1i2I5ryUz5-l4B9jTH3RgBRo

**Comment by teodorescuserban** [comment]
Done.
We just need to protect it somehow.
@alexandru-m-g lets have a call when things get really quiet in my neighborhood :)
Leaving it open so we do not forget.

**Comment by teodorescuserban** [comment]
This is fixed.
Closing.
