### ISSUE TITLE
Raw scraperwiki file not downloading

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-infrastructure#122]
The three rawscraperwiki datasets have resources that will not download. 

https://data.hdx.rwlabs.org/dataset/raw-fts-input
https://data.hdx.rwlabs.org/dataset/raw-scraperwiki-input
https://data.hdx.rwlabs.org/dataset/raw-reliefweb-statistics

Putting the issue here because it may be related to infrastructure and it only affects the three raw scraperwiki datasets that are automatically upload on Thursdays.

**Comment by teodorescuserban** [comment]
The fts should be downloadable.
The other two have not yet updated after the ofs migration.

**Comment by takavarasha** [comment]
For FTS, I am redirected to the login page when I click on the download link: https://data.hdx.rwlabs.org/user/login?came_from=http%3A%2F%2Fdata.hdx.rwlabs.org%2Fdataset%2F9a3efa81-c47a-49ff-a9f7-9f42dbe87237%2Fresource%2F12300d47-dc3b-480d-bcd6-9a2872b26d23%2Fdownload%2Fcsv.zip

**Comment by teodorescuserban** [comment]
Because `Unauthorized to read package raw-fts-input` ?

After you login, it is working?

**Comment by takavarasha** [comment]
No. Its a loop. Login does not succeed, and I am redirected back to https://data.hdx.rwlabs.org/user/login?came_from=http%3A%2F%2Fdata.hdx.rwlabs.org%2Fdataset%2F9a3efa81-c47a-49ff-a9f7-9f42dbe87237%2Fresource%2F12300d47-dc3b-480d-bcd6-9a2872b26d23%2Fdownload%2Fcsv.zip

**Comment by takavarasha** [comment]
The issue has now been reported on the following resource as well: http://data.hdx.rwlabs.org/dataset/860880cc-03df-48e2-80ac-8d7f93911d2e/resource/05b94697-d2aa-49f8-91fb-f3b528b88cc2/download/npl-admin-shp.zip

**Comment by danmihaila** [comment]
@takavarasha I think we know what is the problem, we are working on this. It might be a server related problem. will let you know when is fixed.

**Comment by danmihaila** [comment]
@takavarasha can you please check fts?
I see for these datasets:
https://data.hdx.rwlabs.org/dataset/raw-fts-input
https://data.hdx.rwlabs.org/dataset/raw-scraperwiki-input
https://data.hdx.rwlabs.org/dataset/raw-reliefweb-statistics
the link for resources is pretty strange:
http://data.hdx.rwlabs.org/storage/f/2015-08-07_02-06-01/csv.zip
we moved away of OFS storage to a new format...how are these resources getting into HDX?

**Comment by takavarasha** [comment]
There is a weekly script updating this three datasets. @teodorescuserban can provide more information on that one

**Comment by takavarasha** [comment]
@danmihaila,clicking on the three raw-xxx datasets now gives a server error.

https://data.hdx.rwlabs.org/dataset/raw-fts-input
https://data.hdx.rwlabs.org/dataset/raw-scraperwiki-input
https://data.hdx.rwlabs.org/dataset/raw-reliefweb-statistics

**Comment by danmihaila** [comment]
Are you logged in? They are private resource...i just clicked on first dataset and it is working

**Comment by takavarasha** [comment]
@danmihaila, my bad. I meant to say clicking on the resources inside these three datasets now gives a server error. Before it was going into a loop asking for login.

**Comment by teodorescuserban** [comment]
Fixed long time ago.
