### ISSUE TITLE
Google analytics data for hdx-repo may contain events from test-data

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-infrastructure#130]
I noticed in the google analytics monthly statistics for July that a dataset used to test the geopreview made its way into the top 10 shared datasets. I wonder if it is possible that traffic from our test-data and demo-data servers or other sources is being recorded in the google analytics for the repo. Pinging @amcguire62 and @danmihaila so they can also follow up just incase this is not an issue for here

**Comment by teodorescuserban** [comment]
Related to http auth not being enabled by default on staging.
Fixed long time ago.
