### ISSUE TITLE
nginx configurations

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-infrastructure#185]
I think that some new nginx configuration is causing the below results on both GET: 
![pasted image at 2016_05_27 12_19 am](https://cloud.githubusercontent.com/assets/6586348/15799732/90e52f34-2a6e-11e6-80d6-6c7eb19c476c.png)

and POST:
![pasted image at 2016_05_29 02_23 am](https://cloud.githubusercontent.com/assets/6586348/15799733/90eb45d6-2a6e-11e6-8ad2-c9a1300cee7f.png)

**Comment by teodorescuserban** [comment]
solved
