### ISSUE TITLE
Production snapshot for development

### ISSUE THREAD

**Issue by aalecs** [OCHA-DAP/hdx-infrastructure#23]
Hi Serban, 

Can we have a production snapshot that we, developers, can use on our machines so we can populate the CKAN with data fairly easily.

Thanks!

**Comment by teodorescuserban** [comment]
done.
Thanks for asking that, i will make sure we have some old backup of some datasets lying around dev vm and i will make a script so that you will have 1 button populate db :)
This would be useful after a db clean
Pinging @cjhendrix to see.

**Comment by davidmegginson** [comment]
When you load a new snapshot database, make sure that you rebuild your local Solr search index as well; otherwise, the dataset listings will be messed up:

```
paster --plugin=ckan search-index rebuild --config=/etc/ckan/default/production.ini
```

(Adjust the config-file location as needed.)  Perhaps @teodorescuserban already has this in a deployment script.
