### ISSUE TITLE
Review Serban's current backup strategy and recommend next steps

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-infrastructure#24]

**Comment by davidmegginson** [comment]
@teodorescuserban — could you add the link to this task?

**Comment by davidmegginson** [comment]
Serban said it's still being written, so this issue is temporarily blocked.  We chatted a bit about options, though.

**Comment by teodorescuserban** [comment]
@davidmegginson : https://docs.google.com/document/d/1k_lkdKmHpMYTCWgZcs284SYKInizpKCLc_VK1aVtnb8/edit#heading=h.8zosh2rzb4nf

**Comment by teodorescuserban** [comment]
Pinging @davidmegginson :)

**Comment by davidmegginson** [comment]
The backup strategy looks good, but could we add backup of the server logs as well? Those might be important to us, especially if the site goes down because of a breach or other attack. They could also be needed for access-to-information-type requests.

**Comment by teodorescuserban** [comment]
Good idea.
Please raise it up to critical whenever you want @davidmegginson .

**Comment by teodorescuserban** [comment]
Going to close this one and make another issue for the logs.
Still not backing them up :|
