### ISSUE TITLE
Finalize Docs

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-infrastructure#25]
See trello for details. 

@teodorescuserban Just creating this issue as a reminder of the trello card for docs that is underway.

**Comment by teodorescuserban** [comment]
RFC version is completed.
Link to the docs:
https://docs.google.com/document/d/1k_lkdKmHpMYTCWgZcs284SYKInizpKCLc_VK1aVtnb8/edit
https://docs.google.com/document/d/1F9MgeGurWh83NGEJqNJLo7bEmUTL8VKp9L1XBZ2EZ9o/edit
https://docs.google.com/spreadsheet/ccc?key=0AgVmp3r-qDSddDdWTjNONW1RUVhXZ1h4MzBpWng5aWc&usp=drive_web#gid=0
