### ISSUE TITLE
Review server documentation

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-infrastructure#26]
When Serban completes the docs, review and edit as necessary to make them clear enough for someone familiar with linux to be able to understand and execute essential tasks.  Let's brainstorm on what those tasks include before starting the review.

**Comment by teodorescuserban** [comment]
Scripts are made for the following tasks:

A. cps
- start
- stop
- restart

B. ckan
- start
- stop
- restart
- clean db
- user add
- user remove
- make a user sysadmin
- revoke sysadmin privilege from a user

**Comment by davidmegginson** [comment]
Aidan suggests adding a gameday simulation walking through the docs before we launch. Once with someone from CKAN team, and once with someone from CPS team.

**Comment by davidmegginson** [comment]
Waiting for doc from @teodorescuserban — please reassign to me with doc link once it's ready.

**Comment by teodorescuserban** [comment]
https://docs.google.com/document/d/1k_lkdKmHpMYTCWgZcs284SYKInizpKCLc_VK1aVtnb8/edit
https://docs.google.com/document/d/1F9MgeGurWh83NGEJqNJLo7bEmUTL8VKp9L1XBZ2EZ9o/edit
https://docs.google.com/drawings/d/1ZqAztwDMaUQg46w-s2u9dAJOvK_RSqfyJT4nvmN812I/edit

Please review the permission for gdocs before asking anyone to read them.

**Comment by teodorescuserban** [comment]
Pinging @davidmegginson :)

**Comment by davidmegginson** [comment]
Yes, I'm the blocker on this issue. :-)

**Comment by davidmegginson** [comment]
[HDX Servers Setup](https://docs.google.com/document/d/1k_lkdKmHpMYTCWgZcs284SYKInizpKCLc_VK1aVtnb8/edit) looks good.  One question: do we need to run both Jetty and Tomcat, or could we put both Solr and CPS on the same one?  Doesn't need to be resolved this month; just something to keep in mind.

**Comment by davidmegginson** [comment]
[HDX Server Setup -recipes](https://docs.google.com/document/d/1F9MgeGurWh83NGEJqNJLo7bEmUTL8VKp9L1XBZ2EZ9o/edit) also looks good, though I only skimmed it, without trying to understand every sequence in detail. The best way to test this doc will be by having someone else try to follow it.

**Comment by davidmegginson** [comment]
[HDX Infrastructure dataflow](https://docs.google.com/drawings/d/1ZqAztwDMaUQg46w-s2u9dAJOvK_RSqfyJT4nvmN812I/edit) (which also appears in _HDX Servers Setup_) looks useful. It's not a standard system diagram, but it's probably easier to understand than UML. :-)

**Comment by teodorescuserban** [comment]
@davidmegginson , I asked myself the question about tomcat and jetty. The cons would be: when tomcat is down, ckan search would still run; we need to test another solr install - this one is  liked to jetty in OS packages. The pro: simpler administration, but jetty is very little sysadmin overhead so not really a pro.
