### ISSUE TITLE
Ubuntu 14.04 migration

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#27]
Ubuntu 14.04 is out. This is a long term support version and we need to get it on our servers.

**Comment by davidmegginson** [comment]
I suggest that we delay the migration until after the Warp Coil release in late May, _unless_ there are issues with the current Ubuntu that are creating serious risks or roadblocks.  Please let me know if there are any such issues, @teodorescuserban.

**Comment by teodorescuserban** [comment]
That's why i put it in backlog, @davidmegginson ,
Just keep in mind 13.10 support expires in July (see https://wiki.ubuntu.com/Releases)
Pinging @cjhendrix for that too.

**Comment by davidmegginson** [comment]
When you have a chance, @teodorescuserban, can you put together a few bullets listing the what you think the costs, benefits, and risks of upgrading would be?  The timing will have to be a management decision, but it should be based on the information and recommendations you provide.

I suspect we'd upgrade from the bottom up, so dev first, then staging, then prod.  Does that make sense?

**Comment by teodorescuserban** [comment]
From my first tests, @davidmegginson, it appears the upgrade from 13.10 to 14.04 is failing. As a result, the "migration" will be the install from scratch of our vms as you mentioned (dev -> stag -> prod).
Upgrade might succeed in one-two months (as the 14.04 will be polished) but it is a big risk.

The install from scratch is by far the safest choice, the downtime in this case can be dramatically reduced, but we have to work with our provider as well (if they can give us a new vm each time and after migration they can reclaim the old vm resources) especially for vhosts mapping.

All in all, bullet list is on the way this week (it will be a gdoc, right?).

**Comment by davidmegginson** [comment]
Yes, a Google Doc is perfect.  Thanks for running the test, @teodorescuserban — it probably saved us a lot of grief this close to launch, if we'd gone ahead and tried to upgrade blindly.

**Comment by teodorescuserban** [comment]
Guess what? :)
Google Doc is finally out!
Read it [here](https://docs.google.com/document/d/1eU1RSkiBGsADs3t5MTEEY1wVYpLQw0f3FXBbZjl0qe4/edit?usp=sharing)

**Comment by teodorescuserban** [comment]
Any comment, @davidmegginson , @cjhendrix , @amcguire62 ?

**Comment by teodorescuserban** [comment]
As of now, we have a test ckan on ubuntu 14.04 LTS residing on the backup datacenter:
http://ro.data.hdx.rwlabs.org
Installation went on wthout any particular problems; I still need to set up dataproxy and cps to see isf all is green.
After that , I would require a few hours of testing from our team to spot any weird behaviors, then.. we're good to go.
Either migrate as soon as possible according to plan B from the doc above, or wait for Jan, Feb when we change providers.
Either way, after testing I will close this particular issue.
@amcguire62 , @davidmegginson , @cjhendrix , @danmihaila , comments are welcome!

**Comment by teodorescuserban** [comment]
1. changed the url to https://ro-data.hdx.rwlabs.org/
2. added dataproxy
3. added cps @ https://ro-manage.hdx.rwlabs.org/

pinging @amcguire62 - we're good to go for testing.

**Comment by teodorescuserban** [comment]
Ubuntu 14.04 is used on docker images.
Migration has been successful.
:)tagging @davidmegginson , @danmihaila , @amcguire62 , @cjhendrix

**Comment by cjhendrix** [comment]
:)
