### ISSUE TITLE
Install STAG snapshot on local machine

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-infrastructure#31]
Create a script that will take the snapshot from STAG machine and will drop, create and populate the local Postgres database of CKAN.

**Comment by davidmegginson** [comment]
@danmihaila — is this task critical for the May release? I'm not sure of the impact on the CKAN dev team.

**Comment by danmihaila** [comment]
@davidmegginson - It is not a critical issue, but it will be great tool to have it done when we will start to test and reproduce local the issues from production or staging.
@teodorescuserban - can you give an estimate?

**Comment by teodorescuserban** [comment]
depending on options, it can go as far as 6h.
can do a minimal hardcoded in 2-3 hours I believe.

**Comment by danmihaila** [comment]
I can provide some requirements in case we have a green light :)

**Comment by teodorescuserban** [comment]
Provide them anyway. I _will_ do this if all critical issues are either closed or blocked.

**Comment by teodorescuserban** [comment]
The full snapshot install script has been made to be used on dev and staging.
If you comment out the "rm -rf" line at the end of the script, you have the db backup in /tmp folder.
@danmihaila , please comment on this.

**Comment by teodorescuserban** [comment]
closing, @danmihaila
