### ISSUE TITLE
Automate off-site backup transfer

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#33]
Cron job on our VMs to automate the off-site trasnfer of weekly backups.

**Comment by davidmegginson** [comment]
This is a very high priority for launch — thanks for starting on it.

**Comment by teodorescuserban** [comment]
Done, @davidmegginson .

I created a script on every VM that will sync the backup folder content daily offsite.
The removal of old backups will be done on both local VMs and the destination server (probable on different policies, e.g. on our VMs we dont want to keep a backup more than X months, but on the destination servers we do).

I will make sure the documentation regarding backup policy, as well as details on the destination folder will get updated.
