### ISSUE TITLE
Change FQDNs for HDX staging sites (blocks #36)

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#34]
Will have to contact our provider and our dns manager to update the entries.

**Comment by davidmegginson** [comment]
Blocks #36.

So the task is to change the test.\* staging domains to test-*, e.g. test-manage.hdx.rwlabs.org instead of test.manage.hdx.rwlabs.org.  The reason for the change is that our new wildcard SSL certificates will work for only one level of subdomains.

Waiting for comment on test-\* domains.

**Comment by teodorescuserban** [comment]
I am fine with this. @cjhendrix ? Any comments?
Will send out the emails tomorrow - "no sign is good sign" ;)

**Comment by davidmegginson** [comment]
Here's what @teodorescuserban wrote in his email:
1. Prod vhosts remain unchanged
2. Stag vhosts changes:
   a. test.docs.hdx.rwlabs.org -> test-docs.hdx.rwlabs.org
   b. test.data.hdx.rwlabs.org -> test-data.hdx.rwlabs.org
   c. test.manage.hdx.rwlabs.org -> test-manage.hdx.rwlabs.org
3. Dev vhosts remain unchanged.

**Comment by davidmegginson** [comment]
I'm fine with this arrangement.  Assigning to @cjhendrix for his feedback (please reassign to @teodorescuserban when you're done).

**Comment by cjhendrix** [comment]
Cleared this with Sarah.

Just to be clear, no changes to Prod and Dev vhosts.   Only staging.  I had earlier suggested we might change dev, but I was confused.  :/

**Comment by davidmegginson** [comment]
OK, @teodorescuserban — looks like it's a go!

**Comment by teodorescuserban** [comment]
I sent an email to our dns manager and one email to our provider notifying them for the change.
I've updated the corresponding gdoc in our documentation - [see it here](https://docs.google.com/spreadsheet/ccc?key=0AgVmp3r-qDSddDdWTjNONW1RUVhXZ1h4MzBpWng5aWc&usp=drive_web#gid=0)
Will comment and close the issue once it is really solved :)

@davidmegginson , what do you think about a simple page on old vhosts that is saying about the change and advise the visitors to update their bookmarks, then redirecting to the new hostname?

**Comment by davidmegginson** [comment]
I have no objection to the page, but I'm not sure we'll need it, since the test-\* domains were used only within our team.

**Comment by teodorescuserban** [comment]
i'm still asked what are the creds to enter on stag ckan website... :)
- is very easy to setup - like 20 minutes.

**Comment by davidmegginson** [comment]
OK, then please go ahead.

**Comment by teodorescuserban** [comment]
DNS changes have been made.
The provider added the new hostnames in the list.
I added the new hostnames as alternatives for old vhosts.
Need to test the configs a bit later to see where and what breaks or needs updating (xlsx links will break for example).

**Comment by davidmegginson** [comment]
Just noticed that the new domain names are configured at the ISB and HITEC levels now. @teodorescuserban is just working on configuring the VHOSTS so that they get through to the right web apps.

**Comment by teodorescuserban** [comment]
test.docs.hdx.rwlabs.org is configured as discussed, @davidmegginson 
I will configure the other two late this evening (EET).
Docs do not contain anything of value right now, on the other hand ckan and cps need to work as expected so I need to also check for broken links - I dont want to make server-side redirects or we wont be off the wagon with the old hostnames until next spring. :)

**Comment by teodorescuserban** [comment]
Configured our ckan vhost and observed there are quite a few datasets that are using our local storage and the url is on the old hostname.
Please advise.
Pinging @davidmegginson and @cjhendrix 
A redeploy of ckan content from scratch might be required on stag. (We can rerun the setup script to see what remains and change it by hand).
Assigning to @davidmegginson for resolution.

**Comment by teodorescuserban** [comment]
Because #37 is resolved, I can just go ahead and install from scratch in the other folder, so that we will have two simultaneous instances - and reconfigure nginx to use the new vhost for the other folder - 5 min call should settle this, right @cjhendrix and @davidmegginson ?

**Comment by teodorescuserban** [comment]
In the mean time, a new ckan instance is up with a separate db and solr. ckanSetup script has been run on it with new cps url as well
Some other user-added datasets are still missing (e.g. airports).
Blocked on ckan until I get a call with @cjhendrix and @davidmegginson.
Cps and docs can be changed anytime.

**Comment by davidmegginson** [comment]
This can be fixed with a simple Python or PHP script and the CKAN API, but since it's only for staging, I suggest just starting over.  Over to @cjhendrix for the final call (I assume @teodorescuserban and CJ will discuss this in their call in a few minutes).

**Comment by teodorescuserban** [comment]
In the mean time we have enabled another ckan instance on staging. Our provider has been notified and has added the new fqdn to its' list. However, although the DNS manager has been notified, there is no response so far. Will retry. After this is done, the issue can be closed.

**Comment by cjhendrix** [comment]
Thanks for the update.

**Comment by teodorescuserban** [comment]
@davidmegginson @cjhendrix please help me.
blocker: the dns record for second ckan instance on staging.

**Comment by teodorescuserban** [comment]
solved and closing.

**Comment by cjhendrix** [comment]
Yay!
