### ISSUE TITLE
CPS caching

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/hdx-infrastructure#35]
What problems might exist?

How can we confirm?

**Comment by davidmegginson** [comment]
@teodorescuserban has already confirmed via load testing that CKAN requires some level of caching, and serving static content outside the CKAN webapp.

TBD whether CPS needs caching of generated spreadsheets.

**Comment by teodorescuserban** [comment]
First test proposal: Given any xls file in cps, I will test how many requests per second we can get (actually, the load on the vm is more important) and then, same test but the xls will be cached.

**Comment by teodorescuserban** [comment]
Easy confirmation test: needs shell access to one of our vm.
Logged in stag cps on the browser, hit ctrl+refresh (after each page loads successfully) on /hdx/admin/status/datasets/.
See how java activity raises to 30%.
This is just a simple resources find, not xls generation which will be alot more intensive.
For example, the baseline for zimbabwe took 6 seconds to generate and was eating 30% db cpu, 30% java cpu.

**Comment by davidmegginson** [comment]
That sounds like a good starting point. How much work to get the simplest full XLSX test running?

BTW, I'm nervous that just simple page generation takes the CPU to 30%. We're not going to be having heavy use of CPS for now, but that might be a fair indication of whether CPS can evolve into our analytical web site in the future.

**Comment by teodorescuserban** [comment]
Will do the test next week @davidmegginson . Takes a 1-2 hours to setup. It would be very helpful if we can have two almost identical xslx in CPS - to cache one and not cahce the other. Alternatively I can just test it without cache and then enable cache and test. Please advise.

We are in process of making ui and data manipluation improvs on CPS... didn't raise any hands about optimization (aside Dan with the import complaint) so I'm guess at some point we will have to go back and improve the performance of the code. In the mean time, caching will make it smoother.

**Comment by davidmegginson** [comment]
You could pick the baseline-data XSLX for two different countries: it should be nearly identical (you can verify with a quick skim). Then cache one but not the other.

**Comment by davidmegginson** [comment]
Reassigning to @teodorescuserban for testing.

**Comment by teodorescuserban** [comment]
Preliminary (very basic) tests done.
What I did: I took two baseline countries - Zambia and Zimbabwe. I compared the timings and load - about the same. I cached Zimbabwe only and saw the results. After that, I also cached Zambia and checked the result.
The cache has been set for test on staging server; it has a persistence of only 30 minutes and it caches at the moment ONLY Zimbabwe and Zambia baselines.
Please see video @ http://youtu.be/61JUZ8HkRmM for results.
in the video make sure you keep your eyes on higer part of the window as well, where "top" command is running on staging server.

Reassigning to @davidmegginson for feedback.

**Comment by davidmegginson** [comment]
That was a frightening video, seeing the load average spike to over 0.7 just requesting the same spreadsheet a few times in sequence from CPS. It also demonstrated clearly that caching essentially eliminates that load.  So here's what I think:
- Everything under `/hdx/api/exporter/` gets cached for 24 hours.
- We clear the cache nightly (time TBD, something off-hours for both North American and Africa).
- We have an emergency script/procedure to clear the cache when we need to deploy a change right away (instead of waiting up to 24 hours for it to appear online).
- We monitor performance and server logs for now; in the future, if necessary, we can seed the cache overnight with high-demand spreadsheets (but not yet).

**Comment by teodorescuserban** [comment]
Will do asap and comment here further, @davidmegginson

**Comment by teodorescuserban** [comment]
Update: due to heavy work on cps on both staging and production instances, I am not enabling caching just now, because most likely it will confuse anybody.
Please comment if needed, @davidmegginson 
@JavierTeran , please notify me when the data input curve will drop on either staging or production so I can enable caching (it will expire every 5 minutes initially then the time to live will be increased to 24h).

**Comment by teodorescuserban** [comment]
Assigning to @JavierTeran to confirm and comment on the above post.

**Comment by teodorescuserban** [comment]
Taking the issue back. 
After some discussion and establishing the best way to do it, I made a script that will feed the proxy each day.
Still have some tests to run on it, but very soon it wil fire automatically and will keep the cache full so cps wont feel anything from the clients.

**Comment by teodorescuserban** [comment]
In the mean time, there is a script that builds a static file structure folder from the cps reports.
Today I found out from Godfrey that wfp data is on prod, not staging.

Long story short: cps caching is working at the moment. The only thing I need is the weekly confirmation of the data team that the current week's import was successful so I can proceed and refresh the reports.

Pinging @amcguire62
