### ISSUE TITLE
Our weird logout bug is back

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-infrastructure#38]
![image](https://cloud.githubusercontent.com/assets/1654485/2870295/9608693e-d2bb-11e3-925b-c680fcc1bbbd.png)

This was on staging.  I cleared caches, opened a new tab and tried again with the same result.

**Comment by teodorescuserban** [comment]
I tried without success to replicate this.
Can you please try with different browsers?
What happens after this screenshot?
Do you still have access to your private data, for example user profile?

**Comment by cjhendrix** [comment]
It was only in chrome, so I tried deleting everything (not just caches) and the behavior reverted to normal.  It is not occurring in Firefox or in Chrome Incognito.  

Let's just assume I did a bad job of clearing caches last time.  I may have fixed it in Firefox, but not in Chrome.  

Thanks for taking a look.  Closing.
