### ISSUE TITLE
Enable solr multicore on staging

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#39]
So that we can have more than one instance of ckan at a time on staging.
Useful for snapshots, tests, and so on.
It is also useful to test #1

**Comment by teodorescuserban** [comment]
Done. 
Pinging @cjhendrix for feedback.
Assigned to @davidmegginson for feedback.

**Comment by davidmegginson** [comment]
Sounds like a good idea.  Closing.
