### ISSUE TITLE
Maintenance window sooner

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#41]
@cjhendrix and @davidmegginson , please allow for a scheduled interval for maintenance after code freeze.
What about 20 May?

**Comment by teodorescuserban** [comment]
assigning to @davidmegginson to bump this issue.

**Comment by davidmegginson** [comment]
I have no objection to a scheduled maintenance window, but it's a coordination question:
- It has to work for the CPS team.
- It has to work for the CKAN team.
- It has to work for field trials ( @JavierTeran is leaving for Colombia tomorrow).
- It has to work for any demos that Sarah may have planned in DC or elsewhere.

@amcguire62 — are you the right one to coordinate this? If not, please reassign back to me. I suspect the window will have to be over the weekend, not during the week.

**Comment by teodorescuserban** [comment]
@davidmegginson - let's put it next Monday morning GMT+3 time :) I'm sure no demo in Colombia nor any other demo in US would be active. 

@amcguire62 , agree?
