### ISSUE TITLE
new ckan has some ALL CAPS country names

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-infrastructure#42]

**Comment by teodorescuserban** [comment]
I ran the last version of ckanSetup.

**Comment by cjhendrix** [comment]
Can you check with @aalecs?  Maybe it's better to just keep using the current instance?

**Comment by teodorescuserban** [comment]
the source doc is like that. i asked the data team about it. no response yet.
pinging @davidmegginson

**Comment by teodorescuserban** [comment]
well, what we do on that, @cjhendrix ? @davidmegginson ?
i don't know if the old ckan had the countries all small letters in the first place, but  I can check :)

**Comment by teodorescuserban** [comment]
assigning to @cjhendrix for resolution.

**Comment by cjhendrix** [comment]
Thanks for flagging it again Serban.  As mentioned in the dev team chat, Javier is the only one with edit access to that gdoc.  You'll have to get it from him (or save a copy and edit that one). I'll flag it again in the data team.   My biggest concern is not to screw up prod when we run setup again to create the reamaining countries.

**Comment by teodorescuserban** [comment]
I guess I missed that chat. I will contact Javier directly. In the mean time i looked in cps, and it's the same thing. Some are caps some are not.

**Comment by JavierTeran** [comment]
Sorry I missed this. @teodorescuserban 

Please notify me with an @ Thanks

We worked on the names and put our edits some time ago already in the old CPS spreadsheet:
https://docs.google.com/spreadsheet/ccc?key=0AoSjej3U9V6fdHJzcWNreF8tVDNXTlpaeXl3Z3h3WWc&usp=drive_web#gid=15
This is the approved list of names, includes correct spelling and first letter capital only.

**Comment by teodorescuserban** [comment]
@JavierTeran , last run of ckanSetup script yield correct names of the countries. @cjhendrix , this is now available on drill ckan.

**Comment by teodorescuserban** [comment]
assigning to @cjhendrix to close it. thank you, @JavierTeran

**Comment by teodorescuserban** [comment]
Staging ckan updated as well.

**Comment by teodorescuserban** [comment]
@cjhendrix , I am going to close this.
Pinging @davidmegginson as well.

**Comment by cjhendrix** [comment]
Yes,  I think it is resolved. Serban Teodorescu --- Re: [hdx-infrastructure] new ckan has some ALL CAPS country names (#42) --- From:"Serban Teodorescu" notifications@github.comTo"OCHA-DAP/hdx-infrastructure" hdx-infrastructure@noreply.github.comCc"cjhendrix" hendrix@un.orgDate:Mon, May 12, 2014 08:15SubjectRe: [hdx-infrastructure] new ckan has some ALL CAPS country names (#42)@cjhendrix , I am going to close this.
Pinging @davidmegginson as well.
