### ISSUE TITLE
No user accounts on ckan staging.  

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-infrastructure#43]
The captcha has also stopped working, so no one can create accounts.  

I tried to create them using paster, but with the ckan location change I wasn't able (with my meager skills) to figure out (at least not quickly, I'm sure with more time, I could have found it using the new docs Serban created).

**Comment by teodorescuserban** [comment]
Users created. Details in repo chat.

Recaptcha fixed.

Reassigning to @cjhendrix for validation and closing.

**Comment by teodorescuserban** [comment]
@cjhendrix please close this.
