### ISSUE TITLE
Create script to import raw ReliefWeb data from ScraperWiki to CKAN

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/hdx-infrastructure#44]
@luiscape has his ReliefWeb scraper ready, and we need to start copying the raw RW data to a private CKAN dataset on CKAN staging.

The scraped data is here: https://ds-ec2.scraperwiki.com/bcbk6tq/e81a96f6e040418/http/v1.1/

Having trouble creating a dataset. Will update this task as soon as able.

**Comment by davidmegginson** [comment]
Please put the data in this dataset on staging: http://test-data.hdx.rwlabs.org/dataset/raw-reliefweb-statistics

**Comment by teodorescuserban** [comment]
which file to take, @davidmegginson ? @luiscape ?

**Comment by luiscape** [comment]
I've chatted with @teodorescuserban about this issue. The file is now on CKAN [here](http://test-data.hdx.rwlabs.org/dataset/raw-reliefweb-statistics). It comes from ScraperWiki, as shared by @davidmegginson [above](https://ds-ec2.scraperwiki.com/bcbk6tq/e81a96f6e040418/http/v1.1/).

**Comment by teodorescuserban** [comment]
@davidmegginson decided we should leave the name of the file as it is for now.
Only thing missing is the time of day for the update - send it to enable.
Oh, @luiscape let's not forgot, once the forms are working again, we should put that description to the dataset,
Anyone care to close this? :)

**Comment by luiscape** [comment]
Closing. :full_moon_with_face:

**Comment by luiscape** [comment]
@teodorescuserban Can you please configure your CKAN uploader script to run daily at 11 PM GMT?

Reopening.

**Comment by teodorescuserban** [comment]
done. closing.
please remember, @luiscape and @davidmegginson , this is on stag only!

**Comment by luiscape** [comment]
I'll remember. We'll have to do the same for prod. @teodorescuserban do you have an idea when?

**Comment by teodorescuserban** [comment]
whenever you want @davidmegginson 
In fact, i will just prepare it right now.
:)

**Comment by teodorescuserban** [comment]
Done.
The ckan code on prod seems to force me to choose a country for the dataset...
Maybe @davidmegginson can help uncheck any country on it.
Please let me know when you want this resource to be uploaded atutomatically (only the cron job is to be added).

**Comment by luiscape** [comment]
Hi @teodorescuserban, sorry for sticking my nose here if not welcome, but can't we simply add the scraped data to the "country" `World` for now?

**Comment by teodorescuserban** [comment]
it could, @luiscape 
i just need somebody able to confirm

**Comment by luiscape** [comment]
@teodorescuserban Yes, please add it as a "world" resource. And also set the cron job to update the data daily. :-) Thank you loads!

**Comment by teodorescuserban** [comment]
@luiscape how can I add it as a "world" resource? Please go ahead and change it on production - search for datasets containing "raw" and you shoud find it - or advise.

**Comment by cjhendrix** [comment]
There are some bugs in the current production code base on editing countries.  Let's wait until after deployment today to fix that.

**Comment by luiscape** [comment]
Got it.
