### ISSUE TITLE
Replicate CPS metadata import in staging

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/hdx-infrastructure#45]
@bmichiels has done a reimport of the data team's CPS metadata spreadsheet into CPS dev.  Please use the script he provides in https://github.com/OCHA-DAP/DAP-System/issues/162#issuecomment-42638850 to replicate that reimport in CPS staging — get in touch with Benoît directly with any questions.

**Comment by teodorescuserban** [comment]
done., @davidmegginson . closing.
