### ISSUE TITLE
Some parts of prod ckan db not copied to stag

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-infrastructure#46]
Much of the manual work done by the data team on prod did not come with the db to stag.  We need to know why. In particular, I'm concerned that maybe CKAN_setup is erasing some stuff?  That would be a major problem for us at the moment.  Pinging @aalecs and @danmihaila so they are aware.
# Examples:
## Tags "health" and "children" added by Godfrey 27 days ago

http://data.hdx.rwlabs.org/dataset?q=health+children&sort=score+desc%2C+metadata_modified+desc
-vs-
http://test-data.hdx.rwlabs.org/dataset?q=health+children&sort=score+desc%2C+metadata_modified+desc
## Dataset added by Godfrey 4 days ago

http://data.hdx.rwlabs.org/dataset/kenya-primary-schools
-vs-
http://test-data.hdx.rwlabs.org/dataset/kenya-primary-schools
## Dataset description added by godfrey 27 days ago (see activity stream)

http://data.hdx.rwlabs.org/dataset/children_under_5_moderately_or_severely_underweight
-vs-
http://test-data.hdx.rwlabs.org/dataset/children_under_5_moderately_or_severely_underweight

**Comment by aalecs** [comment]
The script was overriding tags/descriptions until this weekend ... so it's normal :)
Let's retest with the new script and see if it's the case.

**Comment by cjhendrix** [comment]
Ok, so that explains part of it. What about the missing datasets?

**Comment by cjhendrix** [comment]
Issue not present now.  Closing.  Though I do wish we understood what happened.
