### ISSUE TITLE
local storage cleaning

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#47]
you know what script would be very handy? a script that would search the ckan db for local files, make a list and use that list to remove garbage from local storage.

**Comment by teodorescuserban** [comment]
pinging @cjhendrix , @amcguire62 , @davidmegginson , @danmihaila 
it would be great to draw a line for that, and at least for the scrappers archives, define what is too old to care about it - these are candidates for removal.

**Comment by teodorescuserban** [comment]
tunrs out that even when you delete a resource, the file belonging to that resource is not deleted...

**Comment by rufuspollock** [comment]
that's a feature not a bug ;-) (remember you an undelete stuff and you may want archived data to stay around). At the same time, I imagine in some cases you may want to genuinely purge data. If this is an issue you want to raise a bug / feature request on CKAN core.

**Comment by luiscape** [comment]
@teodorescuserban That _feature_ could be useful when analyzing the activity history of a particular dataset. I spend some time investigating this today and thought that could be useful. 

Now, @rgrp even if the resource continues to live in our servers, it seems that the activity list of that resource, with proper links to the files kept, doesn't exist in CKAN. Is that right? For clarity, I mean `package_activity_list` exists, but `resource_activity_list` doesn't. Is there a way to get an equivalent of `resource_activity_list` somewhere?

**Comment by teodorescuserban** [comment]
tagging @cjhendrix - please help me on this one. local filestore is at 2.4 GB now and i need to run hourly backups :(

**Comment by cjhendrix** [comment]
@amcguire62  We are looking at eliminating the backups of previous versions of a file (see #1873 ).   In the meantime, do we still need hourly backups?

**Comment by amcguire62** [comment]
Having discussed with Sarah  - we can move from hourly backups to making a backup every 8 hours. (ie 3 over a 24 hour period) Serban with input from CJ/Dan to decide optimum time.

**Comment by teodorescuserban** [comment]
I can keep doing hourly backups for ckan db and datastore db - they are rather small.
The 8 hours for filestore sounds great though.
