### ISSUE TITLE
Change schedule of import of csv.zip files from scraperwiki to CKAN to Friday 020:0hrs GMT

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-infrastructure#69]
Change the timing of this job from the current Saturdays at 02:00hrs to Fridays at 02:00hrs GMT so that imports of the data into CPS can be carried out on Fridays during the day EST.

**Comment by teodorescuserban** [comment]
Changed as follows:
sw zip: Friday @ 02:00 AM GMT
rw zip: Friday @ 02:03 AM GMT
fts zip: Friday @ 02:06 AM GMT
