### ISSUE TITLE
Cron job to update csv.zip files from scraperwiki to ckan did not run 

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-infrastructure#70]
The scheduled automatic update of the CKAN datasets with the raw csv.zip files from scraper wiki did not run on Saturday 6 Sept 2014. I am not too sure if this is an error or it is by design.

**Comment by teodorescuserban** [comment]
It's a cron job so it is automatic. However, because of the server being shut down (hardware failure), the cronjob has not been executed.
I executed IT manually.
