### ISSUE TITLE
Sarah gets a 401 error from nginx when trying to access staging (in Chrome)

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-infrastructure#72]
Tagging @danmihaila and @amcguire62  so they are aware.

![image](https://cloud.githubusercontent.com/assets/1654485/4219755/63246bce-38fc-11e4-8017-580212a19e89.png)

**Comment by alexandru-m-g** [comment]
Seems to be related to the Basic Authentication that we require on staging. That's the error you get when you don't authenticate.

**Comment by teodorescuserban** [comment]
I agree with Alex. 
It should be solved if chrome is restarted and chrome cache is cleared.

**Comment by teodorescuserban** [comment]
I hear from Sarah that this is not yet solved.
Is the Internet Explorer working as expected?

**Comment by teodorescuserban** [comment]
I was investingating with Javier past week. It seems to be related to users location (more users reported the same issue, each on a different browser, but it worked when asked to use another browser).
I recommend reinstalling the browser at fault (if it's not IE :dancer: )
