### ISSUE TITLE
tracking update issues

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#79]
I am having issues updating the tracking data.
The error reads:

```
sqlalchemy.exc.ProgrammingError: (ProgrammingError) more than one row returned by a subquery used as an expression
 "UPDATE tracking_summary t
                 SET package_id = COALESCE(
                        (SELECT id FROM package p
                        WHERE t.url LIKE  %s || p.name)
                     ,'~~not~found~~')
                 WHERE t.package_id IS NULL
                 AND tracking_type = 'page';" ('%/dataset/',)
```

I remember solving this one with @alexandru-m-g however i do not recall how we did it.

Task would be to do a script that would scream when this error happens and identify where would that be. :)

Pinging @alexandru-m-g - please help me again when you got time (after vacation).

**Comment by teodorescuserban** [comment]
Solved. Nvm, @alexandru-m-g 
Need to document this though.
Leaving it open until after i automate this a bit and document it.

**Comment by ghost** [comment]
Hi @teodorescuserban. I've just run into this issue myself in CKAN trying to run the tracking update paster task. I don't suppose you could point me towards how to were able to fix? or perhaps there is a work-around that you've found?

**Comment by teodorescuserban** [comment]
Hi @george-sattler 
Unfortunately I did not document properly wtf I did.
All I remember is that somehow i had some datasets with **almost** the same name (e.g. `dataset_name` and `dataset-name`) and somehow both got the slug, hence the duplicates.
I will run again over this issue these days and I am going to make sure I document the whole thing (I will also ping you afterwards).

**Comment by ghost** [comment]
Thanks very much for getting back to me - I figured that it was something like two datasets having some similar names. I came up with a workaround that's not ideal but it at least enabled the tracking update task to get passed the issue:
- replace the offending SQL update statement with the version that's currently in master (it's slightly different)
- run the tracking update task
- replace the SQL update statement with it's original

Once I did that, the tracking update task continued to run (for me at least). Still, if you've got another solution it would be great to hear about it.
