### ISSUE TITLE
fix email sending capabilities.

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#80]
I will most likely do the following:
1. talk to our provider to get reverse dns entry for our ip
2. talk to our dns manager to have a separate zone for our subdomain, so that he can configure mail exchanger dns records
3. run through all configs on all our vms and make sure only our subdomain appears.

Pinging @cjhendrix

**Comment by teodorescuserban** [comment]
I sent the request to change our reverse dns entry and this is processing as we speak.
However, it looks that our public IP used to access all sites is different from the IP our smtp session get out.
I made a request for that as well.
In the mean time, I tested hdx -> gmail sending process; it looks like we are hitting a greylist check sometimes - so if you are sending an email and it fails, sending it for the 2nd or 3rd time will work.
This is regarding to https://github.com/OCHA-DAP/hdx-ckan/issues/1273

**Comment by cjhendrix** [comment]
So, are you telling us that right now, if a user submits a membership request, there's a good chance the email won't go a gmail address?
-----Serban Teodorescu notifications@github.com wrote: -----

To: OCHA-DAP/hdx-infrastructure hdx-infrastructure@noreply.github.com
From: Serban Teodorescu notifications@github.comDate: 09/15/2014 03:57PM
Cc: cjhendrix hendrix@un.orgSubject: Re: [hdx-infrastructure] fix email sending capabilities. (#80)I sent the request to change our reverse dns entry and this is processing as we speak.
However, it looks that our public IP used to access all sites is different from the IP our smtp session get out.
I made a request for that as well.In the mean time, I tested hdx -> gmail sending process; it looks like we are hitting a greylist check sometimes - so if you are sending an email and it fails, sending it for the 2nd or 3rd time will work.
This is regarding to 
OCHA-DAP/hdx-ckan#1273—Reply to this email directly or 
view it on GitHub.

**Comment by teodorescuserban** [comment]
@cjhendrix yes

**Comment by teodorescuserban** [comment]
Update status:
Item 1 and 3 from the inital list done.
Additionally, now our outgoing smtp sessions the "normal" source IP.

I will wait a few days to see how this improves the delivered rate.

**Comment by teodorescuserban** [comment]
Update status: still no go; 1/3 or 2/3 emails get rejected.
Our dns provider added MX and TXT infos (but MX appears to work only if subdomain delagation is enabled and TXT about spf was incorrectly added with extra double quotes).
I started a discussion about getting our subdomain delegated so we can manage it ourselves.

**Comment by teodorescuserban** [comment]
Update status: 20/20 working after making postfix use only IPv4.
It appears the gmail IPv6 MX servers have a different policy.

See also:
http://tanguy.ortolo.eu/blog/article109/google-ipv6-smtp-restrictions
http://blog.hqcodeshop.fi/archives/120-Thanks-Google-for-your-new-IPv6-mail-policy.html
http://blog.hqcodeshop.fi/archives/122-Fixing-Googles-new-IPv6-mail-policy-with-Postfix.html
http://postfix.1071664.n5.nabble.com/disable-ipv6-when-sending-to-gmail-td60672.html
and more...

**Comment by teodorescuserban** [comment]
This is not yet a closed issue, because we do not have ALL antispam mechanisms in place.
We need SPF and DKIM.
I installed and configured DKIM on production server.
We only need to have added correctly in our DNS the following:

hdx.rwlabs.org descriptive text "v=DKIM1; k=rsa; ;p=~~MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDLIlTT8u/tV08jDNMZ0t2jE69WS3AeIlFDroqOBjRAqCoyZIH9Da1MM1vp8Ot6Lwbt0LJxVvrRuE21VonqlDgT/Jj1cFiRZazhBAvz+5mGTg6o8mI6w//+V/yCvY+QCi5rT1CYnJxRIJMwWg5ZIyuelcL3y2ZyXCd/R2uP8Xr17QIDAQAB"
hdx.rwlabs.org descriptive text "v=spf1 ip4:85.93.211.39 -all"~~

(note: the key shown above is not the actual key).
and we're done.

**Comment by teodorescuserban** [comment]
dkim in place.

All done :)

Thank you, @cjhendrix for generating this procedure.

**Comment by cjhendrix** [comment]
If we hadn't had the email bug, I wonder how long we would have gone without noticing this one!
