### ISSUE TITLE
enable datastore on prod ckan

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#84]
Done.
@cjhendrix , see [here](https://data.hdx.rwlabs.org/api/3/action/datastore_search?resource_id=_table_metadata); further docs [here](http://data.hdx.rwlabs.org/api/3/action/datastore_search?resource_id=_table_metadata)

**Comment by cjhendrix** [comment]
The two links produce the same result as far as I can tell.  Only difference in the URL is http and https?  But thanks for pointing it out.

**Comment by teodorescuserban** [comment]
just copy / paste failure, @cjhendrix 
the second link should be to: http://docs.ckan.org/en/ckan-2.2/datastore.html
