### ISSUE TITLE
cps static files refresh

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#86]
As per discussion with Godfrey Sept 9th:

[22:46:52] Serban Teodorescu: maybe next month we can switch the modus operandi so that i will run the files refresh script on monday noon GMT UNLESS you are telling me the import is unsuccessful.
[22:47:22] Godfrey Takavarasha: That will be a good idea.

**Comment by teodorescuserban** [comment]
For now, it was runnning manually.
I will change it after asking @amcguire62 and @cjhendrix 
Please comment.

Be careful, once this job becomes an automatic one, we need to advise the import team that is imperative to announce the sysadmins to cancel the job if import was not done (to not get again the same files) or even worse, to not end up with wrong files being served (after a cps report is saved as static file, our web server will NOT ask again cps for that report, it just serve the static file).

**Comment by cjhendrix** [comment]
@teodorescuserban I need to understand this better.  I have a call with data team on Friday and will discuss with them then.  Is it ok?

**Comment by teodorescuserban** [comment]
Of course. We can have a short call as well or you can invite me over in their call when you are talking about this subject.

**Comment by cjhendrix** [comment]
Ok, Serban and I discussed.  It's ok to automate the caching script.  If an import fails, the CPS database will be intact and the caching script will just replace the cache with identical copies.  

However, if the import fails and is not run successfully until after Monday 12:00 GMT, then the data team should request a manual run of the caching script to update.  Pinging @amcguire62 so he is aware.

Also, Serban, can you make sure Godfrey is aware of this.  I can't seem to tag him on this repo, so he is not seeing this discussion.

**Comment by teodorescuserban** [comment]
Closed.
It is now on automatic mode.

**Comment by cjhendrix** [comment]
Pinging @takavarasha to make sure he is aware of this.

**Comment by teodorescuserban** [comment]
I notified @takavarasha on skype soon after closing it.
