### ISSUE TITLE
make a script to stop ckan

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-infrastructure#9]

**Comment by davidmegginson** [comment]
@teodorescuserban — Do we have a wiki article or Google doc about all these scripts?  Apologies if you've already sent me the link five times. :-)

**Comment by teodorescuserban** [comment]
will make a doc about it.

**Comment by davidmegginson** [comment]
+1

**Comment by teodorescuserban** [comment]
closed by 07a8ef784956a6f08ea8e6a16e7f6d05676935ca
