### ISSUE TITLE
Reset API key for an user

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/hdx-infrastructure#95]
Create a script that will reset the API key of an user, changing the setting direct into the database. In case the user is hdx, the change should propagate (manual or automatic) to other scripts (CPS, etc).

**Comment by teodorescuserban** [comment]
Impossible to do in the current config.
Ckan has one set of tools, cps another. They share nothing anymore.
I will consider making cps tool update the api key in config from cli, something like:
cpstool apikey update key=0000-0000-00000-0000
