### ISSUE TITLE
Update UNHCR Real-time Scraper

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-infrastructure#98]
I am not sure where to put it, so I'm putting it here. (Assigned to me.) 

The UNHCR real-time data scraper has stopped working. The likely cause is that UNHCR just updated its API, deprecating the method I was using. (I assume that's a good thing. The method was, indeed, corky.) I'll be updating the scraper on Thursday (16). 

The dataset can se be accessed fine (https://data.hdx.rwlabs.org/dataset/unhcr-information-portal-data). It's just not being updated.

**Comment by teodorescuserban** [comment]
I am not sure where is the origin of that dataset resources.
I am pretty sure it's not coming by the scrappers route (scrapper zip file updated weekly -> published to ckan -> got from cps by importing the data -> publishing into ckan again by cps).
Can you give me more details, @luiscape ?

**Comment by luiscape** [comment]
Hi @teodorescuserban that scraper doesn't feed data to CPS (yet!). It lives solely on ScraperWiki. CKAN simply links to the final CSV output living on ScraperWiki's servers. Take a look at the URL here: https://data.hdx.rwlabs.org/dataset/unhcr-information-portal-data/resource/b8b5670f-ce85-4c50-bb30-aa6003e29f2e

Not the best, but simple solution. The next iteration will actually upload the CSV file into CKAN everyday to trip a bit the dependency on ScraperWiki's servers ...

I updated this scraper today so I'm closing this issue.

**Comment by rufuspollock** [comment]
One comment: it would definitely be sensible to load the CSV files directly into the CKAN _DataStore_ rather than uploading the data to the FileStore (assuming they are "good" CSV files).

**Comment by luiscape** [comment]
@rgrp That would be nice!  On that note, @takavarasha, @cjhendrix or @danmihaila do you know if the DataStore is active and working? I would love to give it a spin.

**Comment by teodorescuserban** [comment]
https://github.com/OCHA-DAP/hdx-infrastructure/issues/84
Please check out the docs first.
The datastore is on but only api calls can load up and query, @luiscape

**Comment by teodorescuserban** [comment]
Also, see:
https://github.com/OCHA-DAP/hdx-ckan/issues/1175
https://github.com/OCHA-DAP/hdx-ckan/issues/1234
https://github.com/OCHA-DAP/hdx-ckan/issues/1235

I am sorry at this point you were not member of the datastore chat room. Thing is, the datastore only provides the functionality and the api; for anything related to ui we have to use datapusher, which is not enabled on prod right now.

In other words, you're on your own for now. :)

**Comment by cjhendrix** [comment]
So, datastore, yes (which is only accessible through the API).  

Datapusher, no.  So uploads through the interface are not put into datastore.

**Comment by luiscape** [comment]
@teodorescuserban + @cjhendrix great! So, how a dataset gets added to the DataStore? And how can I add one via the API (the DataStore API I assume ...)?

**Comment by rufuspollock** [comment]
@luiscape super simple using the API (if you are happy to do a small bit of coding).

To get started here's the example DataStore upload of the original HDX dataset we did as an example for the project back in June:

https://gist.github.com/rgrp/0b24589bd3293234917b

In particular, take a look at:

https://github.com/rgrp/hdx-common-humanitarian-dataset/blob/master/scripts/upload.py

If you are just looking to upload data - i.e. dataset + resource already exist - then you can even ignore most of that file and use:

https://github.com/rgrp/hdx-common-humanitarian-dataset/blob/master/scripts/upload.py#L97

**Comment by luiscape** [comment]
@rgrp That's very nice -- thank you loads for sharing. I'll keep the `upload.py` script in our tool-kit here. What are your opinions @cjhendrix and @teodorescuserban? Having the DataStore API would be very nice to make visualizations and other simple applications on top of certain datasets. When do you think me and @takavarasha can start experimenting with it?

**Comment by rufuspollock** [comment]
@luiscape I think that would be great.

As an example of using the DataStore API I recently scraped the IMF World Economic Outlook data and put it in CKAN DataStore (on the DataHub) and then started work on a super simple dashboard (still very incomplete but for a few hours work it is functional):

http://dev.rufuspollock.org/imf-weo/ (note table is currently a little weird due to a css issue with BS 3 I have not resolved)

Code here: https://github.com/rgrp/imf-weo (README has more info about data etc)

Also relevant:
- There's a decent Node JS / pure JS library for the CKAN DataStore stuff (it is used in the IMF dashboard)
- There's a nice command line tool for getting stuff into CKAN DataStore that is under development - see http://okfnlabs.org/blog/2014/09/11/data-api-for-data-packages-with-dpm-and-ckan.html

**Comment by cjhendrix** [comment]
It's there on prod, so I think you can start your experimenting now.  One limitation may be that all of our indicators are just pointers to CPS, so the data is not kept in the datastore.

**Comment by rufuspollock** [comment]
As I've long suggested there's no reason you couldn't keep data - including indicator data - in the datastore and it could definitely be worth experimenting with :-)

**Comment by luiscape** [comment]
@cjhendrix I can't see the DataStore active anywhere in the prod instance. Can you give me a link to an endpoint? Is the `datastore_active` flag working? If I take a look at this dataset https://data.hdx.rwlabs.org/dataset/internet_users by querying the CKAN API, all the `datastore_active` flags are marked as `false` ...

https://data.hdx.rwlabs.org/api/action/package_show?id=internet_users

**Comment by teodorescuserban** [comment]
As I said, please check the docs first.
https://data.hdx.rwlabs.org/api/3/action/datastore_search?resource_id=_table_metadata
http://docs.ckan.org/en/ckan-2.2/datastore.html#test-the-set-up (but read all file)
datastore has different api calls.

**Comment by cjhendrix** [comment]
@luiscape I don't think there are any datasets that have been loaded via the API, so there wouldn't be anything in the datastore.  Would that explain what you are seeing?  

To automatically push contributed datasets to the datastore, we would have to turn on datapusher (which we did on stag, for testing).  However, this creates some changes in the interface and some (imho) undesirable modifications of the data, that have to be discussed.  I've left that with @amcguire62 for the moment.

**Comment by cjhendrix** [comment]
@rgrp Absolutely.  Just a question of priorities.
