### ISSUE TITLE
Kill the hitec cache!

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-infrastructure#99]
So that private datasets aren't available via URL.  

Let us know if this is likely to have other undesirable consequences.

Tagging @amcguire62

**Comment by teodorescuserban** [comment]
I can email them to clear cache now, however we need to ensure rhe files wont be cached anymore by making sure ckan send proper cache control headers.
I can also add them fron nginx.

**Comment by cjhendrix** [comment]
Made this issue https://github.com/OCHA-DAP/hdx-ckan/issues/1613 for the ckan side of this.

**Comment by teodorescuserban** [comment]
done.
